# frozen_string_literal: true

namespace :db do
  task :reset do
    %w[
      activity_pub_dev
      activity_pub_test
    ].each do |db|
      `dropdb #{db}`
      `createdb #{db}`
      `sequel -m lib/activity_pub/db/migrations postgres://localhost/#{db}`
    end
  end
end
